<h1> Python </h1>
<b><i>Python is a high-level, interpreted, and general-purpose programming language known for its simplicity, readability, and versatility. It was created by Guido van Rossum and first released in 1991. Python's design philosophy emphasizes code readability, making it an excellent language for beginners and experienced developers alike.</i> </b>

Some key features of Python include:

<b> 1. Interpreted Language </b>: Python is interpreted, which means that the code is executed line by line, without the need for compilation. This makes development faster, as you can immediately see the results of your code.

<b>2. Cross-platform:</b> Python is available for various operating systems (Windows, macOS, Linux) and can run on different architectures without modifications.

<b> 3.  Large Standard Library: </b> Python comes with a comprehensive standard library that provides a wide range of modules for various purposes, such as string processing, file I/O, networking, and more.

<b> 4. Dynamic Typing:</b> Python uses dynamic typing, where variable types are determined at runtime. This allows for more flexible and expressive code.

<b> 5. Object-Oriented Programming (OOP):</b> Python supports object-oriented programming, allowing developers to use classes and objects to structure their code and data.

<b> 6. Extensible and Embeddable: </b> Python can be extended with C/C++ libraries, and it can be embedded within other applications to provide scripting capabilities.

<b> 7. Community and Third-party Libr</b>aries: </b> Python has a large and active community, which has contributed to the development of numerous third-party libraries and frameworks for various purposes, such as web development (Django, Flask), data analysis (NumPy, pandas), and machine learning (TensorFlow, scikit learn)

<b> 8. Easy to Learn: </b> Python's syntax is straightforward and concise, making it easy to write and read code.

In [1]:
# hello world print 
print("hello world")

hello world


# range funtion
In Python, range() is a built-in function used to generate a sequence of numbers. It creates an immutable sequence of numbers within a specified range. The range() function can be useful for various purposes, such as creating loops, generating lists, and iterating over elements.<p>It has the following syntax:</p>
<b> range(start, stop, step) </b>

<h5>where:</h5>

<b>start:</b> The starting value of the range (inclusive). If not specified, it defaults to 0.

<b>stop:</b> The ending value of the range (exclusive). This value is not included in the sequence.

<b>step:</b> The step size or the difference between consecutive numbers in the sequence. If not specified, it defaults to 1.
    
Here are a few examples to demonstrate how range() works:


In [2]:
# Generating a sequence of numbers from 0 to 4 (exclusive) with a default step of 1:
rg=range(4)
for i in rg:
    print(i)

0
1
2
3


In [3]:
# Generating a sequence of even numbers from 2 to 10 (exclusive) with a step of 2:
for num in range(2, 10, 2):
    print(num)


2
4
6
8


In [4]:
# Creating a list containing numbers from 5 to 15 (exclusive) with a default step of 1:
my_list = list(range(5, 15))
print(my_list)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [5]:
# Generating a sequence of numbers in reverse order from 10 to 1 (exclusive) with a step of -1:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


Note that the range() function does not generate a list directly; it creates a range object. If you need a list, you can convert the range to a list using list(range(...)) as shown in the third example. In Python 2.x, the range() function returns a list directly, but in Python 3.x, it returns a range object for better memory efficiency when dealing with large ranges.


## Operater

- Arithmetic Operators
- Relational Operators
- Logical Operators
- Bitwise Operators
- Assignment Operators
- Membership Operators

In [1]:
# Arithmetric Operators
print(5+6)

print(5-6)

print(5*6)

print(5/2)

print(5//2)

print(5%2)

print(5**2)

11
-1
30
2.5
2
1
25


In [2]:
# Relational Operators
print(4>5)

print(4<5)

print(4>=4)

print(4<=4)

print(4==4)

print(4!=4)

False
True
True
True
True
False


In [3]:
# Logical Operators
print(1 and 0)

print(1 or 0)

print(not 1)

0
1
False


In [4]:
# Assignment Operators

# =
# a = 2

a = 2

# a = a % 2
a %= 2

print(a)

0


## bitwise operater
Bitwise operator are used to pefrom oparation at binaly digit. these operators are not commonly used and are used only in special oppeications where optimized use of storage is required.

In [1]:
a=7
b=10
print("~a=",~a) # compliment operator
print("a&b=",a&b) # and operator
print("a|b=",a|b) # or operator
print("a^b=",a^b) # xor operator
print("a>>2=",a>>2) # right shift operator
print("a<<=",a<<2) # left shift operator

~a= -8
a&b= 2
a|b= 15
a^b= 13
a>>2= 1
a<<= 28


### Membership Operators in Python
the membarhip operators are usefull to test for membership in a sequence such as fring ,lists,tuples and dictionaraies . 

In [3]:
str= "you are a good boy "
print("are" in str) # in operator 
print("are" not in str) # not in operator

True
False


### Implicit Type Conversion in Python
in the implicit type conversion python automatically converts one data type into another data type.

In [1]:
a=5
b=2
result=a/b
print(result) # implicit type convertion 
type(result)

2.5


float

In [3]:
v = "hello"
k = "world"
value = v+" "+k
print(value)
type(value)

hello world


str

#### Q. Program - Find the sum of a 3 digit number entered by the user

In [6]:
number = int(input('Enter a 3 digit number'))

a = number%10

number = number//10
b = number%10

number = number //10
c = number%10

print("sum of a 3 digit number is",a+b+c)


Enter a 3 digit number345
sum of a 3 digit number is 12


### Explicit Type Conversion in Python
in the cast/explicit type conversion ,progammer converts data type into another data type 

In [5]:
a=5
b=2
result=a/b
int_result=int(result)
print(int_result)

2


In [6]:
a=20
b="7"
b=int(b)
result=a/b
print(result)

2.857142857142857


### output statment or print funtion 
print() funtion the print() function used to print the specified message to the output screen/device .the massege can be a string or any other object.

In [8]:
print("dibyendu sasmala is good boy ") # print("string")


dibyendu sasmala is good boy 


In [9]:
data= [10,20,-50,21.30,"ds"] # print(object)
print(data)

[10, 20, -50, 21.3, 'ds']


In [10]:
print("ds","ms","ps",sep='**') # print("string",sep ='')

ds**ms**ps


In [11]:
print("dibyendu",end='\n') # print("string",end='')
print("sasmal")

dibyendu
sasmal


In [12]:
a=10
b=20
print(a,b,sep='$$') # print(variable list )

10$$20


In [13]:
name="dibyendu sasmal"
age=23
print("my name is",name,"and my age is ",age) # print("sting",variable)

my name is dibyendu sasmal and my age is  23


### Getting input from user or Input Statement or input Function in Python
input() this funtion is used to accept input from keybord.

In [14]:
name = input("what is your name ")
print(name)

what is your name dibyendu
dibyendu


### Escape Sequence in Python
this control charecter used to move the cursoor a print charecter such as ' , " . \ and so on 

In [3]:
print("dibyendu \n sasmal")

dibyendu 
 sasmal


In [1]:
print("dibyendu \"sasmal\" ")

dibyendu "sasmal" 


## Modules in Python

- math
- keywords
- random
- datetime

In [1]:
# math
import math

math.sqrt(196)

14.0

In [2]:
# keyword
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
# random
import random
print(random.randint(1,100))

56


In [4]:
# datetime
import datetime
print(datetime.datetime.now())

2023-11-08 20:30:39.884014


In [5]:
help('modules')


Please wait a moment while I gather a list of all available modules...



C:\Users\HP\anaconda3\lib\site-packages\nltk\twitter\__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(
C:\Users\HP\anaconda3\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
C:\Users\HP\anaconda3\lib\pkgutil.py:108: VisibleDeprecationWarning:

zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    



Cython              concurrent          mpmath              snowballstemmer
IPython             conda               msgpack             socket
OpenSSL             conda_build         msilib              socketserver
PIL                 conda_content_trust msvcrt              socks
PyQt5               conda_env           multidict           sockshandler
TBB                 conda_pack          multimethod         sortedcollections
__future__          conda_package_handling multipledispatch    sortedcontainers
_abc                conda_token         multiprocessing     soupsieve
_aix_support        conda_verify        munkres             sphinx
_argon2_cffi_bindings configparser        mypy_extensions     spyder
_ast                constantly          mysql               spyder_kernels
_asyncio            contextlib          mysqlx              sqlalchemy
_bisect             contextvars         nacl                sqlite3
_black_version      cookiecutter        navigator_updater   sre_com

### If Statement in Python 
it is used to execute an instraction or block of instractions only if a condition is fulfiled 

In [17]:
if 5>2:
    print("getterthan")
print("rest of the code")

getterthan
rest of the code


In [3]:
if 6<7:
    print("lessthan")
print("rest of the code")

lessthan
rest of the code


In [19]:
a= int(input("enter a number getterthan 2: "))
if a>2:
    print("you enter the number",a)
print("rest of the code")


enter a number getterthan 2: 5
you enter the number 5
rest of the code


### Write a program to display "Hello" if a number entered by user is a multiple of five , otherwise print "Bye"

In [4]:
number= int(input("enter a number"))
if number%5==0:
    print("Hello")
else:
    print("Bye")

enter a number25
Hello


### Write a program to calculate the electricity bill (accept number of unit from user) according to the following criteria :
***
             Unit                                                     Price  
First 100 units                                               no charge
Next 100 units                                              Rs 5 per unit
After 200 units                                             Rs 10 per unit
(For example if input unit is 350 than total bill amount is Rs2000)
***

In [15]:
unit=int(input("enter how many unit bill you have: "))
amu=0
if unit<100:
    amu=0
    print("you save electric like pro and you don't have to pay any amaunt")
if unit>100 and 200>=unit:
    amu=amu+(unit-100)*5
    print("your bill is: ",amu)
if unit>200:
    amu=500+(unit-200)*10
    print("your bill is",amu)

enter how many unit bill you have: 200
your bill is:  500


### Nested if Statement in Python

a=int(input("enter a numeber: "))
b=int(input("enter second number: "))
c=int(input("enter third number: "))
if b>a: # jodi eii condition ta na true hoy tahole porer condition run hobe ni or statmentao print hobeni 
    print("b is greater than a") 
    if c<a: # jodi condition true na hole statment print hobena;
        print("a is greater than c")
print("rest of the code")

## if Statement with Logical Operator in Python


In [20]:
if 5>2 and 7>3:
    print("if statment with and logicaloperator")
print("rest of the code")

if statment with and logicaloperator
rest of the code


In [21]:
if 5>2 or 7<3:
    print("if statment with or logicaloperator")
print("rest of the code")

if statment with or logicaloperator
rest of the code


In [4]:
if 5 !=2:
    print("not logical operator")

not logical operator


## if else Statement in Python
if else statment is used when a differant sequence of instructions is to be executed .

In [22]:
if 5>2:
    print("greater than")
else:
    print("less than ")
print("rest of the code")

greater than
rest of the code


In [23]:
a= int(input("enter a number greater than 2"))
if a>2:
    print("a is the carect input you given by")
else:
    print("your input is wrong")
print("rest of the code")

enter a number greater than 25
a is the carect input you given by
rest of the code


### nested if else statment
in nested if else statment ,an entire if else construct is written within either the body of the if statment or the body of an else statment.

In [2]:
a=13
b=6
c=11
d=3
if a>b:
    if(b>c):
        print("d is greater than c ")
    else:
        print("c is greter than d")
else:
    print("a is greater than b")
print("rest of the code")

c is greter than d
rest of the code


### if elif and if elif else Statement in Python
to show a multiway decision based on several conditions , we use if elif else statment 

In [25]:
a=1
b=3
c=2
if a>b:
    print("a is greater than b")
elif b>c:
    print("b is greater than c")
else:
    print("c is greater than all")


b is greater than c


In [26]:
day= "tuesday"
if day == "monday":
    print("today is monday")
elif day == "tuesday":
    print("today is tuesday")
elif day=="wednesday":
    print

today is tuesday


# loop control statment
loop control statment are used when a saction of code many either be executed a fixed number of times ,or while some condition is true 

## While Loop and Nested while Loop in Python
the while loop kecps repeating on action until an associated condition returns false.

In [27]:
a=0
while a<=5:
    print(a)
    a+=1
print("rest of the code")

0
1
2
3
4
5
rest of the code


In [3]:
a=1
while a<=10:
    print("dibyendu sasmal",a)
    a+=1
print("rest of the code")

dibyendu sasmal 1
dibyendu sasmal 2
dibyendu sasmal 3
dibyendu sasmal 4
dibyendu sasmal 5
dibyendu sasmal 6
dibyendu sasmal 7
dibyendu sasmal 8
dibyendu sasmal 9
dibyendu sasmal 10
rest of the code


In [29]:
a=0
while a<=20:
    print(a)
    a+=2
print("rest of the code")

0
2
4
6
8
10
12
14
16
18
20
rest of the code


In [30]:
a=2
while a<=10:
    print(a)
    a+=1
else:
    print("while codition is false now") #while loop with else
print("rest of the code")

2
3
4
5
6
7
8
9
10
while codition is false now
rest of the code


In [2]:
i=0
while True :
    print(i) # this infinite loop don't work beacuse jupyter lab don't have True keyword
    if i<=5:
        break
print("rest of the code")

0
rest of the code


## nested while loop


In [32]:
i=1
while i<=3:
    print("outer loop",i)
    i+=1
    j=1
    while j<=5:
        print("inner loop",j)
        j+=1
print("rest of the code")

outer loop 1
inner loop 1
inner loop 2
inner loop 3
inner loop 4
inner loop 5
outer loop 2
inner loop 1
inner loop 2
inner loop 3
inner loop 4
inner loop 5
outer loop 3
inner loop 1
inner loop 2
inner loop 3
inner loop 4
inner loop 5
rest of the code


In [33]:
# Display multiplication table using nested while  in Python language
n=0
while n<20:
    print("this is ",n+1,"nd order mutiplication tabel")
    n+=1
    i=1
    while i<=10:
        print(i*n)
        i+=1
print("complite the tabel")

this is  1 nd order mutiplication tabel
1
2
3
4
5
6
7
8
9
10
this is  2 nd order mutiplication tabel
2
4
6
8
10
12
14
16
18
20
this is  3 nd order mutiplication tabel
3
6
9
12
15
18
21
24
27
30
this is  4 nd order mutiplication tabel
4
8
12
16
20
24
28
32
36
40
this is  5 nd order mutiplication tabel
5
10
15
20
25
30
35
40
45
50
this is  6 nd order mutiplication tabel
6
12
18
24
30
36
42
48
54
60
this is  7 nd order mutiplication tabel
7
14
21
28
35
42
49
56
63
70
this is  8 nd order mutiplication tabel
8
16
24
32
40
48
56
64
72
80
this is  9 nd order mutiplication tabel
9
18
27
36
45
54
63
72
81
90
this is  10 nd order mutiplication tabel
10
20
30
40
50
60
70
80
90
100
this is  11 nd order mutiplication tabel
11
22
33
44
55
66
77
88
99
110
this is  12 nd order mutiplication tabel
12
24
36
48
60
72
84
96
108
120
this is  13 nd order mutiplication tabel
13
26
39
52
65
78
91
104
117
130
this is  14 nd order mutiplication tabel
14
28
42
56
70
84
98
112
126
140
this is  15 nd order mutipli

In [3]:
#this is a program to display multiplication table
#example for nested-while loop in Python
i=0
while i<=10:
    i+=1
    j=1
    while j<=12:
        print (i*j)
        j+=1
        

1
2
3
4
5
6
7
8
9
10
11
12
2
4
6
8
10
12
14
16
18
20
22
24
3
6
9
12
15
18
21
24
27
30
33
36
4
8
12
16
20
24
28
32
36
40
44
48
5
10
15
20
25
30
35
40
45
50
55
60
6
12
18
24
30
36
42
48
54
60
66
72
7
14
21
28
35
42
49
56
63
70
77
84
8
16
24
32
40
48
56
64
72
80
88
96
9
18
27
36
45
54
63
72
81
90
99
108
10
20
30
40
50
60
70
80
90
100
110
120
11
22
33
44
55
66
77
88
99
110
121
132


## for loop and Nested for Loop in Python

In [10]:
data = "dibyendu sasmal"
for a in data:
    print(a)

d
i
b
y
e
n
d
u
 
s
a
s
m
a
l


In [11]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
data = "dibyendu sasmal"
ab = len(data)
for a in range(ab): #string index er janne ekhane all eliment print hobe 
    #ekhane 0 index theke 9 porjanto index number tori hobe tai somostho element print kora somvob 
    print(a,"data",data[a])

0 data d
1 data i
2 data b
3 data y
4 data e
5 data n
6 data d
7 data u
8 data  
9 data s
10 data a
11 data s
12 data m
13 data a
14 data l


In [4]:
# for loop with else part
its="dibyendu"
for i in its:
    print(i)
else:
    print("this is else part")
print("rest of the code")

d
i
b
y
e
n
d
u
this is else part
rest of the code


In [6]:
# nested for loop
for i in range(3):
    print("outer loop",i)
    for j in range(5):
        print("inner loop",j)

outer loop 0
inner loop 0
inner loop 1
inner loop 2
inner loop 3
inner loop 4
outer loop 1
inner loop 0
inner loop 1
inner loop 2
inner loop 3
inner loop 4
outer loop 2
inner loop 0
inner loop 1
inner loop 2
inner loop 3
inner loop 4


## Break Statement and Continue Statement in Python

In [9]:
# break statment
for i in range(5):
    print(i) # if statment opore likhechi tai ekhane 3 porjanto print hobe
    if i==3:
        break

0
1
2
3


In [8]:
# break statment
for i in range(5):
    if i==3:
        break
    print(i) # if statment er niche likhechi tai ar 3 print hoyni 

0
1
2


In [7]:
# continue statment
for i in range(5):
    if i==3:
        continue
    print(i) # continue statment e janne 3 tike skip koreche ekhane 

0
1
2
4


### Array in Python

In [ ]:
import array                                         # from import array*                         eta jupyte labe suport korena 
st_roll=array.array('i',[101,102,103,104,105])       # st_roll=array('i',[101,102,103,104,105])
for i in st_roll:                                    # for i in st_roll: 
    print(i)                                         #     print(i)

### Accessing Array using for Loop Array Module in Python

In [ ]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])

### Accessing Array using for while Array Module in Python

In [ ]:
import array
stu_roll=array.array('i',[100,107,109,101,102,103,104,105])
n=len(stu_roll)
i=0
while i<n:
    print("index",i,"=",stu_roll[i])
    i+=1

### append Method in Python

In [61]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
stu_roll.append(110)
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])

index 0 = 100
index 1 = 101
index 2 = 102
index 3 = 103
index 4 = 104
index 5 = 105
index 6 = 110


In [ ]:
#getting input from user 
import array
stu_roll = array.array('i',[])
n=int(input("enter how many element"))
for i in range(n):                         # gettin input from user
    stu_roll.append(int(input("element")))
for i in range(len(stu_roll)): # print the result
    print(stu_roll[i])

### Getting Array Input from user using while Loop in Python


In [ ]:
import array
stu_roll = array.array('i',[])
n=int(input("enter how many element"))
i=0
while i<n:
    stu_roll.append(int(input("element")))
    i+=1
j=0
while j<len(stu_roll):
    print(stu_roll[j])
    j+=1

In [66]:
import array
stu_roll = array.array('i',[])
n=int(input("enter how many element"))
for i in range(n):
    stu_roll.append(int(input("element")))
print(stu_roll)
print("after accessing array eliment")
for i in range(n):
    print(stu_roll[i])

enter how many element3
element10
element11
element12
array('i', [10, 11, 12])
after accessing array eliment
10
11
12


### Slicing on Arrays in Python

In [1]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])
# affter slicing this array
a=stu_roll[1:3]
for i in a:
    print(i)

index 0 = 100
index 1 = 101
index 2 = 102
index 3 = 103
index 4 = 104
index 5 = 105
101
102


In [2]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])
# affter slicing this array
a=stu_roll[:3]
for i in a:
    print(i)

index 0 = 100
index 1 = 101
index 2 = 102
index 3 = 103
index 4 = 104
index 5 = 105
100
101
102


In [3]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])
# affter slicing this array
a=stu_roll[2:]
for i in a:
    print(i)

index 0 = 100
index 1 = 101
index 2 = 102
index 3 = 103
index 4 = 104
index 5 = 105
102
103
104
105


In [4]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])
# affter slicing this array
a=stu_roll[1:5:2]
for i in a:
    print(i)

index 0 = 100
index 1 = 101
index 2 = 102
index 3 = 103
index 4 = 104
index 5 = 105
101
103


In [ ]:
import array
stu_roll=array.array('i',[100,101,102,103,104,105])
n=len(stu_roll)
for i in range(n):
    print("index",i,"=",stu_roll[i])
# affter slicing this array
a=stu_roll[:-3]
for i in a:
    print(i)

In [ ]:
!pip install numpy


### One Dimensional Numpy Array using array Function

In [13]:
import numpy
stu_roll = numpy.array([101,102,103,104,105,106])
for i in stu_roll:
    print(i)

101
102
103
104
105
106


In [14]:
import numpy
stu_roll = numpy.array(["dibyendu","sasmal","machgeria","brahmanbasan","daspur",102,102.002])
for i in stu_roll:
    print(i)

dibyendu
sasmal
machgeria
brahmanbasan
daspur
102
102.002


In [15]:
import numpy
a=numpy.array([101,102,103,104,105,106])
n =len(a)
i=0
while i<n:
    print(a[i]) # n[i] likle error dey , ar ami barbarr n used kori
    i+=1
    

101
102
103
104
105
106


### Numpy One Dimensional Array using linspace Function

In [ ]:
import numpy
n = numpy.linspace(1,6,10)
for i in n:
    print(i)

In [ ]:
import numpy
n = numpy.linspace(1,6,10)
exl = len(n)
i=0
while i<exl:
    print(n[i])
    i+=1

### Numpy One Dimensional Array using logspace Function in Python 

In [ ]:
import numpy
log= numpy.logspace(1,3,5)
for i in log:
    print(i)

In [ ]:
import numpy
log= numpy.logspace(1,3,5,base=12)
for i in log:
    print(i)

In [ ]:
import numpy
log= numpy.logspace(1,3,5)
ln = len(log)
i=0
while i<ln:
    print(log[i])
    i+=1

### Numpy One Dimensional Array using arange Function in Python

In [ ]:
import numpy
a = numpy.arange(1,10,2)
an = len(a)
i=0
while i<an:
    print(a[i])
    i+=1

In [ ]:
import numpy
a = numpy.arange(1,10,2)
an = len(a)
i=0
while i<an:
    print('index',i,'=',a[i])
    i+=1

### Numpy One Dimensional Array using ones Function in Python

In [12]:
import numpy
a = numpy.ones(5)
b =len(a)
i=0
while i<b:
    print(a[i])
    i+=1

1.0
1.0
1.0
1.0
1.0


### Numpy zeros Dimensional Array using ones Function in Python

In [ ]:
import numpy
a = numpy.zeros(5)
b =len(a)
i=0
print(a) #print the zeros array
while i<b:
    print(a[i]) # one by one eliment acssesing from the array
    i+=1

## Math Operations on Arrays using Numpy in Python 


In [ ]:
import numpy
a = numpy.array([101,102,103,104,105,106,107,108,109])
b = a+5
c = a-5
d = a*5
e = a/5
print(b)
print(c)
print(d)
print(e)

In [ ]:
import numpy
a = numpy.array([101,102,103,104,105,106,107,108,109])
b = a+5
ln = len(a)
for i in range(ln):
    print("index",i,"=",b[i])

### Comparing Numpy Arrays in Python

In [34]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result = a==b
print(result)

[False False  True False False  True]


In [35]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result = a<b
print(result)

[False  True False  True False False]


In [36]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result = a>b
print(result)

[ True False False False  True False]


### any and all Functions in Python

In [37]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result = a==b
any(result)

True

In [38]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result = a==b
all(result)

False

### where Function in Python 

In [44]:
import numpy
a = numpy.array([101,102,103,104,105,106])
b = numpy.array([100,200,103,140,60,106])
result =numpy.where(a>b,a,b)
print(result)

[101 200 103 140 105 106]


### nonzero Function in Python 

In [45]:
import numpy
a = numpy.array([101,0,103,104,0,106,107,0,109,0])
result=numpy.nonzero(a)
print(result)

(array([0, 2, 3, 5, 6, 8], dtype=int64),)


### Aliasing Array in Python

In [46]:
import numpy
a = numpy.array([101,0,103,104,0,106,107,0,109,0])
b=a
print(a,id(a))
print(b,id(b))

[101   0 103 104   0 106 107   0 109   0] 2506721137552
[101   0 103 104   0 106 107   0 109   0] 2506721137552


### view Method and copy Method in Python

In [5]:
# view method
import numpy
a = numpy.array([101,0,103,104,0,106,107,109,0])
b=a.view()
a[1]=20
b[4]=30
a[8]=110
print(a,"\n",id(a))
print(b,"\n",id(b))

[101  20 103 104  30 106 107 109 110] 
 2952634778896
[101  20 103 104  30 106 107 109 110] 
 2952706929840


In [56]:
# copy method
import numpy
a = numpy.array([101,0,103,104,0,106,107,109,0])
b=a.copy()
a[1]=20
b[4]=30
a[8]=110
print(a,"\n",id(a))
print(b,"\n",id(b))

[101  20 103 104   0 106 107 109 110] 
 2506737560720
[101   0 103 104  30 106 107 109   0] 
 2506738138448


### Getting input from user in Numpy One Dimensional Array using loop Python

In [81]:
import numpy
n=int(input("enter how many eliment you want: "))
a=numpy.zeros(n)
for i in range(n):
    b=int(input("eliment: "))
    a[i]=b
print(a)
print("after accessing array value")
for i in range(n):
    print(a[i])

enter how many eliment you want: 3
eliment: 10
eliment: 20
eliment: 30
[10. 20. 30.]
after accessing array value
10.0
20.0
30.0


In [4]:
import numpy
n=int(input("enter how many eliment you want: "))
a=numpy.zeros(n, dtype=int)
i=0
while i<n:
    b=int(input("eliment"))
    a[i]=b
    i+=1
j=0
while j<n:
    print(a[j])
    j+=1

enter how many eliment you want: 3
eliment10
eliment20
eliment30
10
20
30


### Two Dimensional Numpy Array using array Function in Python

In [5]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]])
print(a[1][2])

70


In [6]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]])
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

10
20
30
40
50
60
70
80


In [7]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]])
a[1][2]=100
print(a[1][2])

100


In [8]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]],dtype=float) # data type change 
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

10.0
20.0
30.0
40.0
50.0
60.0
70.0
80.0


In [9]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]],dtype=str) # string data type 
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

10
20
30
40
50
60
70
80


In [10]:
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]])
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

int32
10
20
30
40
50
60
70
80


In [11]:
#implcit change data type 
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,8.0]])
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

float64
10.0
20.0
30.0
40.0
50.0
60.0
70.0
8.0


In [8]:
for i in range(5):
    print("outer loop",i)
    for j in range(10):
        print(j)

outer loop 0
0
1
2
3
4
5
6
7
8
9
outer loop 1
0
1
2
3
4
5
6
7
8
9
outer loop 2
0
1
2
3
4
5
6
7
8
9
outer loop 3
0
1
2
3
4
5
6
7
8
9
outer loop 4
0
1
2
3
4
5
6
7
8
9


In [13]:
for i in range(5):
    print("outer loop ",i)
    for j in range(i):
        print("inner loop = ",j)

outer loop  0
outer loop  1
inner loop =  0
outer loop  2
inner loop =  0
inner loop =  1
outer loop  3
inner loop =  0
inner loop =  1
inner loop =  2
outer loop  4
inner loop =  0
inner loop =  1
inner loop =  2
inner loop =  3


### Accessing Numpy Two Dimensional Array using for Loop in Python

In [16]:
# with out index
import numpy
a=numpy.array([[10,20,30,40],
              [50,60,70,80]],dtype=int)
for row in a:
    for clumn in row:
        print(clumn)
    print()


10
20
30
40

50
60
70
80



### Accessing Numpy Two Dimensional Array using for Loop in Python with index

In [27]:
# with index 
import numpy
a = numpy.array([[10,20,30,40],
                 [50,60,70,80]])
n=len(a)
# print(n) output: 2 or index number is 0,1
for i in range(n):
    #print("index a",i,a[i]) output: [10 20 30 40] [50 60 70 80]
    for j in range(len(a[i])):
        print("index a","[",i,"]","[",j,"]","=",a[i][j])
 

index a [ 0 ] [ 0 ] = 10
index a [ 0 ] [ 1 ] = 20
index a [ 0 ] [ 2 ] = 30
index a [ 0 ] [ 3 ] = 40
index a [ 1 ] [ 0 ] = 50
index a [ 1 ] [ 1 ] = 60
index a [ 1 ] [ 2 ] = 70
index a [ 1 ] [ 3 ] = 80


### Accessing Numpy Two Dimensional Array using while Loop in Python

In [32]:
# accessing with index
import numpy
a = numpy.array([[10,20,30,40],
                 [50,60,70,80]])
i=len(a)
i=0
while i<n:
    j=0
    while j<len(a[i]):
        print("index a","[",i,"]","[",j,"]","=",a[i][j])
        j+=1
    i+=1 #nested while loop er first loop(outer loop) increment statment inner loop er pore sothik indention er sathe bosate hoy

index a [ 0 ] [ 0 ] = 10
index a [ 0 ] [ 1 ] = 20
index a [ 0 ] [ 2 ] = 30
index a [ 0 ] [ 3 ] = 40
index a [ 1 ] [ 0 ] = 50
index a [ 1 ] [ 1 ] = 60
index a [ 1 ] [ 2 ] = 70
index a [ 1 ] [ 3 ] = 80


In [37]:
# accessing with out index
import numpy 
a = numpy.array([[1,2,3,4],[5,6,7,8]])
n=len(a)
i=0
while i<n:
    print(a[i])
    j=0
    while j<len(a[i]):
        print(a[i][j])
        j+=1
    i+=1
#when you used while loop then accessing 2d array with out index is not possibel

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [43]:
import numpy
a=numpy.zeros((3,4),dtype=int)
n=len(a)
for i in range(n):
    for j in range(len(a[i])):
        print(a[i][j])
print(a)

0
0
0
0
0
0
0
0
0
0
0
0
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
#with out index
import numpy
a=numpy.zeros((3,4),dtype=int)
for i in a:
    for j in i:
        print(j)

0
0
0
0
0
0
0
0
0
0
0
0


### ones() funtion using creating 2d array

In [48]:
import numpy as np
a=np.ones((3,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [50]:
#accessing array using loop
import numpy as np
a= np.ones((3,3),dtype=int)
for r in a:
    for j in r:
        print(j)

1
1
1
1
1
1
1
1
1


In [55]:
import numpy as np
a= np.ones((3,3),dtype=int)
n=len(a)
for i in range(n):
    for j in range(len(a[i])):
        print(a[i][j])

1
1
1
1
1
1
1
1
1


## reshape Function and flatten Method in Python

In [59]:
# 1d to 2d convertion
import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=np.reshape(a,(2,6)) # here need accurate shape value
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [60]:
# 1d to 3d convertion
import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=np.reshape(a,(2,3,2))
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [62]:
# 2d to 1d convertion 
import numpy as np
a=np.array([[1,2,3,4],[5,6,6,7]])
d=np.reshape(a,(8))
print(d)

[1 2 3 4 5 6 6 7]


In [67]:
#3d to 1d
import numpy as np
a=np.array([[[ 1,2],
              [ 3,4],
              [ 5,6]],
             [[ 7,8],
              [ 9,10],
              [11,12]]])
b = np.reshape(a,(12))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
# using flatten() funtion
import numpy as np
a=np.array([[1,2,3,4],[5,6,6,7]])
d=a.flatten()
print(d)

[1 2 3 4 5 6 6 7]


## Input from User in Numpy Two Dimensional Array using for Loop in Python 

In [2]:
import numpy
m=int(input("enter how many row you want to"))
n=int(input("ente how many column you want to "))
a=numpy.zeros((m,n))
print(a)
u=len(a)
for i in range(u):
    for j in range(len(a[i])):
        x=int(input("enter the element"))
        a[i][j]=x
print(a)
#for i in range(u):
 #   for j in range(len(a[i])):
 #       print(a[i][j])

enter how many row you want to2
ente how many column you want to 2
[[0. 0.]
 [0. 0.]]
enter the element1
enter the element2
enter the element3
enter the element4
[[1. 2.]
 [3. 4.]]


In [76]:
# with out index
import numpy
m=int(input("enter how many row you want to"))
n=int(input("ente how many column you want to "))
a=numpy.zeros((m,n))
print(a)
u=len(a)
for i in range(u):
    for j in range(len(a[i])):
        x=int(input("enter the element"))
        a[i][j]=x
print(a)
for r in a:
    for c in r:
        print(c)

enter how many row you want to3
ente how many column you want to 2
[[0. 0.]
 [0. 0.]
 [0. 0.]]
enter the element1
enter the element2
enter the element3
enter the element4
enter the element5
enter the element6
[[1. 2.]
 [3. 4.]
 [5. 6.]]
1.0
2.0
3.0
4.0
5.0
6.0


## Input from User in Numpy Two Dimensional Array using while Loop in Python

In [81]:
import numpy
m=int(input("enter how many row you want to"))
n=int(input("ente how many column you want to "))
a=numpy.zeros((m,n),dtype=int)
u=len(a)
i=0
while i<u:
    while j<len(a[i]):
        x=int(input("element"))
        a[i][j]=x
        j+=1
    i+=1
print(a)

enter how many row you want to3
ente how many column you want to 2
[[0 0]
 [0 0]
 [0 0]]


### Slicing on Two Dimensional Array in Python 

In [10]:
import numpy
a= numpy.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("orginal array")
print(a)
print("after slicing")
n=a[0:1,0:1]
print(n)

orginal array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
after slicing
[[1]]


In [19]:
# only practis 
import numpy
m=int(input("enter the number of row"))
n=int(input("enter the number of column"))
a=numpy.zeros((m,n))
b=len(a)
for i in range(b):
    for j in range(len(a[i])):
        x=(input("element"))
        a[i][j]=x
for i in range(b):
    for j in range(len(a[i])):
        print(a[i][j])
            

enter the number of row2
enter the number of column3
element1
element2
element3
element4
element5
element6
1.0
2.0
3.0
4.0
5.0
6.0
